package com.axonivy.connectivity.client;

import jakarta.annotation.Generated;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.7
 * 2020-10-22T09:44:48.365+02:00
 * Generated source version: 3.3.7
 *
 */
@WebService(targetNamespace = "http://connectivity.axonivy.com/", name = "technicalBackendService")
@XmlSeeAlso({ObjectFactory.class, process.webservice.ivy.ivyteam.ch.client.ObjectFactory.class, org.w3._2001.xmlschema.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2020-10-22T09:44:48.365+02:00", comments = "Apache CXF 3.3.7")
public interface TechnicalBackendService {

    @WebMethod
    @WebResult(name = "longRunningBatchOperationResponse", targetNamespace = "http://connectivity.axonivy.com/", partName = "parameters")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2020-10-22T09:44:48.365+02:00")
    public LongRunningBatchOperationResponse longRunningBatchOperation(

        @WebParam(partName = "parameters", name = "longRunningBatchOperation", targetNamespace = "http://connectivity.axonivy.com/")
        LongRunningBatchOperation parameters
    ) throws WebServiceProcessTechnicalException;
}
