package nike.project.client;

import javax.annotation.Generated;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2020-01-28T14:02:24.870+01:00
 * Generated source version: 3.3.4
 *
 */
@WebService(targetNamespace = "http://project.nike/", name = "NikeFactory")
@XmlSeeAlso({ObjectFactory.class, process.webservice.ivy.ivyteam.ch.client.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2020-01-28T14:02:24.870+01:00", comments = "Apache CXF 3.3.4")
public interface NikeFactory {

    @WebMethod
    @WebResult(name = "produceResponse", targetNamespace = "http://project.nike/", partName = "parameters")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2020-01-28T14:02:24.870+01:00")
    public ProduceResponse produce(

        @WebParam(partName = "parameters", name = "produce", targetNamespace = "http://project.nike/")
        Produce parameters
    ) throws WebServiceProcessTechnicalException;
}
