package nike.project.client;

import java.net.URL;
import javax.annotation.Generated;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2020-01-28T14:02:24.892+01:00
 * Generated source version: 3.3.4
 *
 */
@WebServiceClient(name = "NikeFactoryService",
                  wsdlLocation = "NikeFactoryService.wsdl",
                  targetNamespace = "http://project.nike/")
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2020-01-28T14:02:24.892+01:00", comments = "Apache CXF 3.3.4")
public class NikeFactoryService extends Service {

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2020-01-28T14:02:24.892+01:00")
    public final static URL WSDL_LOCATION;

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2020-01-28T14:02:24.892+01:00")
    public final static QName SERVICE = new QName("http://project.nike/", "NikeFactoryService");
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2020-01-28T14:02:24.892+01:00")
    public final static QName NikeFactoryPort = new QName("http://project.nike/", "NikeFactoryPort");
    static {
        URL url = NikeFactoryService.class.getResource("NikeFactoryService.wsdl");
        if (url == null) {
            url = NikeFactoryService.class.getClassLoader().getResource("NikeFactoryService.wsdl");
        }
        if (url == null) {
            java.util.logging.Logger.getLogger(NikeFactoryService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "NikeFactoryService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2020-01-28T14:02:24.892+01:00")
    public NikeFactoryService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2020-01-28T14:02:24.892+01:00")
    public NikeFactoryService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2020-01-28T14:02:24.892+01:00")
    public NikeFactoryService() {
        super(WSDL_LOCATION, SERVICE);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2020-01-28T14:02:24.892+01:00")
    public NikeFactoryService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2020-01-28T14:02:24.892+01:00")
    public NikeFactoryService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2020-01-28T14:02:24.892+01:00")
    public NikeFactoryService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns NikeFactory
     */
    @WebEndpoint(name = "NikeFactoryPort")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2020-01-28T14:02:24.892+01:00")
    public NikeFactory getNikeFactoryPort() {
        return super.getPort(NikeFactoryPort, NikeFactory.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NikeFactory
     */
    @WebEndpoint(name = "NikeFactoryPort")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2020-01-28T14:02:24.892+01:00")
    public NikeFactory getNikeFactoryPort(WebServiceFeature... features) {
        return super.getPort(NikeFactoryPort, NikeFactory.class, features);
    }

}
