
package nike.project.client;

import javax.annotation.Generated;
import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.4
 * 2020-01-28T14:02:24.838+01:00
 * Generated source version: 3.3.4
 */

@WebFault(name = "TechnicalException", targetNamespace = "ch.ivyteam.ivy.webservice.process")
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2020-01-28T14:02:24.838+01:00", comments = "Apache CXF 3.3.4")
public class WebServiceProcessTechnicalException extends Exception {

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2020-01-28T14:02:24.838+01:00")
    private java.lang.String technicalException;

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2020-01-28T14:02:24.838+01:00")
    public WebServiceProcessTechnicalException() {
        super();
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2020-01-28T14:02:24.838+01:00")
    public WebServiceProcessTechnicalException(String message) {
        super(message);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2020-01-28T14:02:24.838+01:00")
    public WebServiceProcessTechnicalException(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2020-01-28T14:02:24.838+01:00")
    public WebServiceProcessTechnicalException(String message, java.lang.String technicalException) {
        super(message);
        this.technicalException = technicalException;
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2020-01-28T14:02:24.838+01:00")
    public WebServiceProcessTechnicalException(String message, java.lang.String technicalException, java.lang.Throwable cause) {
        super(message, cause);
        this.technicalException = technicalException;
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2020-01-28T14:02:24.838+01:00")
    public java.lang.String getFaultInfo() {
        return this.technicalException;
    }
}
