package com.axonivy.connectivity.soap.interceptor.client;

import jakarta.annotation.Generated;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-09-13T13:31:43.830+02:00
 * Generated source version: 3.3.2
 *
 */
@WebService(targetNamespace = "http://interceptor.soap.connectivity.axonivy.com/", name = "serviceWithException")
@XmlSeeAlso({ObjectFactory.class, process.webservice.ivy.ivyteam.ch.client.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-09-13T13:31:43.830+02:00", comments = "Apache CXF 3.3.2")
public interface ServiceWithException {

    @WebMethod
    @WebResult(name = "callResponse", targetNamespace = "http://interceptor.soap.connectivity.axonivy.com/", partName = "parameters")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-09-13T13:31:43.830+02:00")
    public CallResponse call(

        @WebParam(partName = "parameters", name = "call", targetNamespace = "http://interceptor.soap.connectivity.axonivy.com/")
        Call parameters
    ) throws WebServiceProcessTechnicalException, WebServiceProcessBusinessException;
}
