package com.axonivy.connectivity.soap.service.client;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.2
 * 2018-04-12T14:55:43.369+02:00
 * Generated source version: 3.2.2
 *
 */
@WebServiceClient(name = "PersonServiceService",
                  wsdlLocation = "PersonServiceService.wsdl",
                  targetNamespace = "http://service.soap.connectivity.axonivy.com/")
public class PersonServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.soap.connectivity.axonivy.com/", "PersonServiceService");
    public final static QName PersonServicePort = new QName("http://service.soap.connectivity.axonivy.com/", "PersonServicePort");
    static {
        URL url = PersonServiceService.class.getResource("PersonServiceService.wsdl");
        if (url == null) {
            url = PersonServiceService.class.getClassLoader().getResource("PersonServiceService.wsdl");
        }
        if (url == null) {
            java.util.logging.Logger.getLogger(PersonServiceService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "PersonServiceService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PersonServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PersonServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PersonServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public PersonServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public PersonServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public PersonServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns PersonService
     */
    @WebEndpoint(name = "PersonServicePort")
    public PersonService getPersonServicePort() {
        return super.getPort(PersonServicePort, PersonService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PersonService
     */
    @WebEndpoint(name = "PersonServicePort")
    public PersonService getPersonServicePort(WebServiceFeature... features) {
        return super.getPort(PersonServicePort, PersonService.class, features);
    }

}
