package com.axonivy.connectivity.soap.service.client;

import java.net.URL;
import jakarta.annotation.Generated;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.6.11
 * 2026-06-17T07:38:27.641+02:00
 * Generated source version: 3.6.11
 *
 */
@WebServiceClient(name = "PersonServiceService",
                  wsdlLocation = "personService.wsdl",
                  targetNamespace = "http://service.soap.connectivity.axonivy.com/")
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-06-17T07:38:27.641+02:00", comments = "Apache CXF 3.6.11")
public class PersonServiceService extends Service {

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-06-17T07:38:27.641+02:00")
    public static final URL WSDL_LOCATION;

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-06-17T07:38:27.641+02:00")
    public static final QName SERVICE = new QName("http://service.soap.connectivity.axonivy.com/", "PersonServiceService");
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-06-17T07:38:27.641+02:00")
    public static final QName PersonServicePort = new QName("http://service.soap.connectivity.axonivy.com/", "PersonServicePort");
    static {
        URL url = PersonServiceService.class.getResource("personService.wsdl");
        if (url == null) {
            url = PersonServiceService.class.getClassLoader().getResource("personService.wsdl");
        }
        if (url == null) {
            java.util.logging.Logger.getLogger(PersonServiceService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "personService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-06-17T07:38:27.641+02:00")
    public PersonServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-06-17T07:38:27.641+02:00")
    public PersonServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-06-17T07:38:27.641+02:00")
    public PersonServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-06-17T07:38:27.641+02:00")
    public PersonServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-06-17T07:38:27.641+02:00")
    public PersonServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-06-17T07:38:27.641+02:00")
    public PersonServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns PersonService
     */
    @WebEndpoint(name = "PersonServicePort")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-06-17T07:38:27.641+02:00")
    public PersonService getPersonServicePort() {
        return super.getPort(PersonServicePort, PersonService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PersonService
     */
    @WebEndpoint(name = "PersonServicePort")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-06-17T07:38:27.641+02:00")
    public PersonService getPersonServicePort(WebServiceFeature... features) {
        return super.getPort(PersonServicePort, PersonService.class, features);
    }

}
