package com.axonivy.connectivity.soap.service.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.2
 * 2018-04-12T14:55:43.346+02:00
 * Generated source version: 3.2.2
 *
 */
@WebService(targetNamespace = "http://service.soap.connectivity.axonivy.com/", name = "PersonService")
@XmlSeeAlso({ObjectFactory.class, process.webservice.ivy.ivyteam.ch.client.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PersonService {

    @WebMethod
    @WebResult(name = "addPersonResponse", targetNamespace = "http://service.soap.connectivity.axonivy.com/", partName = "parameters")
    public AddPersonResponse addPerson(
        @WebParam(partName = "parameters", name = "addPerson", targetNamespace = "http://service.soap.connectivity.axonivy.com/")
        AddPerson parameters
    ) throws WebServiceProcessTechnicalException;

    @WebMethod
    @WebResult(name = "getPersonsResponse", targetNamespace = "http://service.soap.connectivity.axonivy.com/", partName = "parameters")
    public GetPersonsResponse getPersons(
        @WebParam(partName = "parameters", name = "getPersons", targetNamespace = "http://service.soap.connectivity.axonivy.com/")
        GetPersons parameters
    ) throws WebServiceProcessTechnicalException;

    @WebMethod
    @WebResult(name = "deletePersonResponse", targetNamespace = "http://service.soap.connectivity.axonivy.com/", partName = "parameters")
    public DeletePersonResponse deletePerson(
        @WebParam(partName = "parameters", name = "deletePerson", targetNamespace = "http://service.soap.connectivity.axonivy.com/")
        DeletePerson parameters
    ) throws WebServiceProcessTechnicalException;
}
