package ch.ivyteam.testservice.policy.greeter.client;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.2
 * 2018-04-10T14:27:36.834+02:00
 * Generated source version: 3.2.2
 *
 */
@WebService(targetNamespace = "http://policy.testservice.ivyteam.ch/", name = "SecureGreetPolicyService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SecureGreetPolicyService {

    @WebMethod
    @WebResult(name = "greetResponse", targetNamespace = "http://policy.testservice.ivyteam.ch/", partName = "parameters")
    public GreetResponse greet(
        @WebParam(partName = "parameters", name = "greet", targetNamespace = "http://policy.testservice.ivyteam.ch/")
        Greet parameters
    );
}
