package ch.ivyteam.testservice.policy.greeter.client;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.2
 * 2018-04-10T14:27:36.866+02:00
 * Generated source version: 3.2.2
 *
 */
@WebServiceClient(name = "SecureGreetPolicyServiceService",
                  wsdlLocation = "SecureGreetPolicyServiceService.wsdl",
                  targetNamespace = "http://policy.testservice.ivyteam.ch/")
public class SecureGreetPolicyServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://policy.testservice.ivyteam.ch/", "SecureGreetPolicyServiceService");
    public final static QName SecureGreetPolicyServicePort = new QName("http://policy.testservice.ivyteam.ch/", "SecureGreetPolicyServicePort");
    static {
        URL url = SecureGreetPolicyServiceService.class.getResource("SecureGreetPolicyServiceService.wsdl");
        if (url == null) {
            url = SecureGreetPolicyServiceService.class.getClassLoader().getResource("SecureGreetPolicyServiceService.wsdl");
        }
        if (url == null) {
            java.util.logging.Logger.getLogger(SecureGreetPolicyServiceService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "SecureGreetPolicyServiceService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SecureGreetPolicyServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SecureGreetPolicyServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SecureGreetPolicyServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public SecureGreetPolicyServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SecureGreetPolicyServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SecureGreetPolicyServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns SecureGreetPolicyService
     */
    @WebEndpoint(name = "SecureGreetPolicyServicePort")
    public SecureGreetPolicyService getSecureGreetPolicyServicePort() {
        return super.getPort(SecureGreetPolicyServicePort, SecureGreetPolicyService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SecureGreetPolicyService
     */
    @WebEndpoint(name = "SecureGreetPolicyServicePort")
    public SecureGreetPolicyService getSecureGreetPolicyServicePort(WebServiceFeature... features) {
        return super.getPort(SecureGreetPolicyServicePort, SecureGreetPolicyService.class, features);
    }

}
