# yaml-language-server: $schema=https://json-schema.axonivy.com/14.0-dev/config/webservice-clients-2.json
WebServiceClients:
  createOrderService:
    Name: createOrderService
    ServiceClass: com.axonivy.connectivity.createorder.client.CreateOrderService
    WsdlUrl: http://localhost:8081/designer/ws/connectivity-demos/162492A1649E72DF?WSDL
    Endpoints:
      CreateOrderPort:
        - http://localhost:8081/designer/ws/connectivity-demos/162492A1649E72DF
    LegacyId: 1624D62D6426F325
  policyGreeter:
    Name: policyGreeter
    ServiceClass: ch.ivyteam.testservice.policy.greeter.client.SecureGreetPolicyServiceService
    WsdlUrl: http://test-webservices.ivyteam.io:8080/country-service/webservices/greet-policy-wss?wsdl
    Features:
      - ch.ivyteam.ivy.webservice.exec.cxf.feature.policy.IgnorePolicyFeature
    Properties:
      policy.disabled: http://schemas.xmlsoap.org/ws/2005/07/securitypolicy:SupportingTokens
      endpoint.cache: 'false'
    Endpoints:
      SecureGreetPolicyServicePort:
        - http://test-webservices.ivyteam.io:8080/country-service/webservices/greet-policy-wss
    LegacyId: 162AF1AE2B935160
