package com.axonivy.connectivity.createorder.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.2
 * 2018-03-22T13:27:34.737+01:00
 * Generated source version: 3.2.2
 *
 */
@WebService(targetNamespace = "http://connectivity.axonivy.com/", name = "createOrder")
@XmlSeeAlso({ObjectFactory.class, com.axonivy.connectivity.createorder.exception.client.ObjectFactory.class})
public interface CreateOrder {

    @WebMethod
    @RequestWrapper(localName = "call", targetNamespace = "http://connectivity.axonivy.com/", className = "com.axonivy.connectivity.createorder.client.Call")
    @ResponseWrapper(localName = "callResponse", targetNamespace = "http://connectivity.axonivy.com/", className = "com.axonivy.connectivity.createorder.client.CallResponse")
    @WebResult(name = "task", targetNamespace = "")
    public com.axonivy.connectivity.createorder.client.Task call(
        @WebParam(name = "order", targetNamespace = "")
        com.axonivy.connectivity.createorder.client.Order order
    ) throws WebServiceProcessTechnicalException;
}
