package com.axonivy.connectivity.createorder.client;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.2
 * 2018-03-22T13:27:34.769+01:00
 * Generated source version: 3.2.2
 *
 */
@WebServiceClient(name = "createOrderService",
                  wsdlLocation = "createOrderService.wsdl",
                  targetNamespace = "http://connectivity.axonivy.com/")
public class CreateOrderService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://connectivity.axonivy.com/", "createOrderService");
    public final static QName CreateOrderPort = new QName("http://connectivity.axonivy.com/", "createOrderPort");
    static {
        URL url = CreateOrderService.class.getResource("createOrderService.wsdl");
        if (url == null) {
            url = CreateOrderService.class.getClassLoader().getResource("createOrderService.wsdl");
        }
        if (url == null) {
            java.util.logging.Logger.getLogger(CreateOrderService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "createOrderService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CreateOrderService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CreateOrderService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CreateOrderService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public CreateOrderService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CreateOrderService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CreateOrderService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns CreateOrder
     */
    @WebEndpoint(name = "createOrderPort")
    public CreateOrder getCreateOrderPort() {
        return super.getPort(CreateOrderPort, CreateOrder.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CreateOrder
     */
    @WebEndpoint(name = "createOrderPort")
    public CreateOrder getCreateOrderPort(WebServiceFeature... features) {
        return super.getPort(CreateOrderPort, CreateOrder.class, features);
    }

}
