
package com.axonivy.connectivity.createorder.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.2
 * 2018-03-22T13:27:34.712+01:00
 * Generated source version: 3.2.2
 */

@WebFault(name = "TechnicalException", targetNamespace = "ch.ivyteam.ivy.webservice.process")
public class WebServiceProcessTechnicalException extends Exception {

    private java.lang.String technicalException;

    public WebServiceProcessTechnicalException() {
        super();
    }

    public WebServiceProcessTechnicalException(String message) {
        super(message);
    }

    public WebServiceProcessTechnicalException(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public WebServiceProcessTechnicalException(String message, java.lang.String technicalException) {
        super(message);
        this.technicalException = technicalException;
    }

    public WebServiceProcessTechnicalException(String message, java.lang.String technicalException, java.lang.Throwable cause) {
        super(message, cause);
        this.technicalException = technicalException;
    }

    public java.lang.String getFaultInfo() {
        return this.technicalException;
    }
}
